# Generated by Django 3.1.3 on 2020-11-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpr_db', '0002_camp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='camp',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
