# Generated by Django 3.1.3 on 2020-11-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpr_db', '0003_employee_registration_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='state',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='zip',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
