# Generated by Django 3.1.4 on 2020-12-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpr_db', '0005_auto_20201126_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now=True)),
                ('payment_received', models.CharField(max_length=1)),
                ('notes', models.CharField(default='n/a', max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='zip',
            new_name='zipcode',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='zip',
            new_name='zipcode',
        ),
        migrations.AddField(
            model_name='student',
            name='bday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(default='n/a', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='n/a', max_length=2),
        ),
        migrations.AlterField(
            model_name='camp',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='campregistration',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpr_db.camp'),
        ),
        migrations.AddField(
            model_name='campregistration',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fpr_db.student'),
        ),
    ]
