# Generated by Django 3.1.4 on 2020-12-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpr_db', '0007_auto_20201204_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campregistration',
            name='camp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fpr_db.camp'),
        ),
        migrations.AlterField(
            model_name='campregistration',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fpr_db.student'),
        ),
    ]
