# Generated by Django 3.1.4 on 2020-12-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpr_db', '0008_auto_20201204_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='cost',
            field=models.FloatField(default='0.00'),
        ),
    ]
